const CURRENT='zahraaDecisionSession', HISTORY='zahraaDecisionSessionsHistory';
const $=id=>document.getElementById(id);
function show(id){document.querySelectorAll('.screen').forEach(s=>s.classList.remove('active'));$(id)?.classList.add('active');scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>{if(b.dataset.go==='approval-screen')$('decision-heading').textContent='القرار المقترح: '+($('approved-decision').value||'غير محدد');show(b.dataset.go)});
function getSession(){try{return JSON.parse(localStorage.getItem(CURRENT)||'{}')}catch{return {}}}
function getHistory(){try{return JSON.parse(localStorage.getItem(HISTORY)||'[]')}catch{return []}}
function saveSession(s){localStorage.setItem(CURRENT,JSON.stringify(s));if(!s.sessionId)return;const h=getHistory();const i=h.findIndex(x=>x.sessionId===s.sessionId);const v={...s,updatedAt:new Date().toISOString()};i>=0?h[i]=v:h.unshift(v);localStorage.setItem(HISTORY,JSON.stringify(h.slice(0,20)))}
function esc(v=''){return String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
async function callGemini(task,session){const r=await fetch('/api/gemini',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({task,session})});let d;try{d=await r.json()}catch{throw Error('لم يُرجع الخادم استجابة صحيحة.')}if(!r.ok)throw Error(d.error||'تعذر الاتصال بمحرك Gemini.');return d.text}
function loading(b,on,t){if(!b)return;if(on){b.dataset.old=b.textContent;b.textContent=t;b.disabled=true}else{b.textContent=b.dataset.old||b.textContent;b.disabled=false}}
const example={subject:'الرياضيات',gradeLevel:'الصف السادس الابتدائي',lessonTopic:'مقارنة الكسور مختلفة المقامات',lessonDuration:'45',studentCount:'28',studentLevel:'متفاوت',learningGoal:'أن يقارن الطلاب بين كسرين مختلفي المقامات، وأن يبرروا المقارنة باستخدام تمثيل بصري أو كسور متكافئة.',classChallenge:'بعض الطلاب يخلطون بين البسط والمقام، وبعضهم يستخدم الضرب التبادلي دون فهم، بينما يستطيع بعض الطلاب الحل لكنهم لا يقدمون تبريرًا واضحًا.',availableResources:'سبورة وأوراق عمل فقط.',additionalConstraints:'تجنب عزل المتعثرين وعدم تنفيذ أكثر من انتقال تنظيمي واحد. الأولوية للفهم المفاهيمي ثم التبرير.'};
$('fill-example').onclick=()=>{Object.entries(example).forEach(([k,v])=>{if($(k))$(k).value=v});$('form-message').className='success';$('form-message').textContent='تمت تعبئة المثال التجريبي.'};
$('context-form').onsubmit=async e=>{e.preventDefault();for(const id of ['subject','gradeLevel','lessonTopic','lessonDuration','learningGoal','classChallenge'])if(!$(id).value.trim()){ $('form-message').className='error';$('form-message').textContent='يرجى إكمال الحقول الأساسية.';return }const b=e.submitter,s={sessionId:crypto.randomUUID?.()||String(Date.now()),sessionStatus:'CONTEXT_SUBMITTED',teacherApproval:false};['subject','gradeLevel','lessonTopic','lessonDuration','studentCount','studentLevel','learningGoal','classChallenge','availableResources','additionalConstraints'].forEach(id=>s[id]=$(id).value.trim());saveSession(s);loading(b,true,'جاري التحليل...');try{const t=await callGemini('adaptive_question',s);s.adaptiveQuestion=t;s.sessionStatus='QUESTION_GENERATED';saveSession(s);const q=(label)=>{const line=t.split('\n').find(x=>x.trim().startsWith(label));return line?line.split(':').slice(1).join(':').trim():''};$('question-type').textContent=q('نوع السؤال')||'سؤال تكيفي';$('question-text').textContent=q('السؤال')||t;$('question-why').innerHTML='<strong>لماذا نسأل؟</strong> '+esc(q('لماذا نسأل')||'لأن الإجابة ستؤثر في القرار.');show('adaptive-screen')}catch(err){$('form-message').className='error';$('form-message').textContent=err.message}finally{loading(b,false)}};
$('not-sure').onclick=()=>$('adaptive-answer').value='لست متأكدًا. أحتاج إلى فحص تشخيصي قصير يساعدني على تحديد المستوى.';
$('save-answer').onclick=async()=>{const a=$('adaptive-answer').value.trim();if(!a)return alert('اكتب إجابة قبل المتابعة.');const b=$('save-answer'),s=getSession();s.adaptiveAnswer=a;s.sessionStatus='QUESTION_ANSWERED';saveSession(s);loading(b,true,'جاري إعداد الملخص...');try{const t=await callGemini('context_summary',s);s.contextSummary=t;s.sessionStatus='SUMMARY_GENERATED';saveSession(s);$('summary-content').innerHTML='<div class="generated">'+esc(t)+'</div>';$('summary-preview').classList.remove('hidden')}catch(err){alert(err.message)}finally{loading(b,false)}};
$('approve-summary').onclick=async()=>{const b=$('approve-summary'),s=getSession();if(!s.contextSummary)return alert('أنشئ الملخص أولًا.');loading(b,true,'جاري إنشاء البدائل...');try{const t=await callGemini('alternatives',s);s.alternatives=t;s.sessionStatus='ALTERNATIVES_GENERATED';saveSession(s);$('alternatives-content').innerHTML='<div class="generated">'+esc(t)+'</div>';show('alternatives-screen')}catch(err){alert(err.message)}finally{loading(b,false)}};
$('generate-plan').onclick=async()=>{if(!$('teacher-approval').checked){$('approval-message').className='error';$('approval-message').textContent='لا يمكن إنشاء الخطة قبل الموافقة.';return}const b=$('generate-plan'),s=getSession();s.teacherApproval=true;s.approvedDecision=$('approved-decision').value.trim()||'قرار المعلم';s.sessionStatus='DECISION_APPROVED';saveSession(s);loading(b,true,'جاري إنشاء الخطة...');try{const t=await callGemini('implementation_plan',s);s.implementationPlan=t;s.sessionStatus='PLAN_GENERATED';saveSession(s);$('plan-content').innerHTML='<div class="generated">'+esc(t)+'</div>';$('plan-preview').classList.remove('hidden');$('approval-message').className='success';$('approval-message').textContent='تم إنشاء الخطة بنجاح.'}catch(err){$('approval-message').className='error';$('approval-message').textContent=err.message}finally{loading(b,false)}};
$('show-sessions').onclick=()=>showSessions();
function showSessions(){let m=$('sessions-modal');if(!m){m=document.createElement('div');m.id='sessions-modal';m.className='sessions-modal hidden';m.innerHTML='<div class="sessions-overlay"></div><div class="card sessions-box"><div class="heading"><h2>جلساتي السابقة</h2><button id="close-sessions">إغلاق</button></div><div id="sessions-list"></div></div>';document.body.appendChild(m);m.querySelector('.sessions-overlay').onclick=()=>m.classList.add('hidden');$('close-sessions').onclick=()=>m.classList.add('hidden')}const h=getHistory(),list=$('sessions-list');if(!h.length)list.innerHTML='<p>لا توجد جلسات محفوظة حتى الآن.</p>';else list.innerHTML=h.map(s=>'<div class="session-card"><h3>'+esc(s.lessonTopic||'جلسة')+'</h3><p>'+esc(s.subject||'')+' — '+esc(s.gradeLevel||'')+'</p><div class="actions"><button class="primary open-session" data-id="'+esc(s.sessionId)+'">فتح</button><button class="secondary delete-session" data-id="'+esc(s.sessionId)+'">حذف</button></div></div>').join('');list.querySelectorAll('.open-session').forEach(b=>b.onclick=()=>{const s=h.find(x=>x.sessionId===b.dataset.id);if(!s)return;localStorage.setItem(CURRENT,JSON.stringify(s));['subject','gradeLevel','lessonTopic','lessonDuration','studentCount','studentLevel','learningGoal','classChallenge','availableResources','additionalConstraints'].forEach(id=>{if($(id))$(id).value=s[id]||''});m.classList.add('hidden');show('context-screen')});list.querySelectorAll('.delete-session').forEach(b=>b.onclick=()=>{localStorage.setItem(HISTORY,JSON.stringify(getHistory().filter(x=>x.sessionId!==b.dataset.id)));showSessions()});m.classList.remove('hidden')}
